[2025-09-24T00:54:09.680+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-24T00:54:09.689+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab1.load_model_task manual__2025-09-24T00:53:59.377325+00:00 [queued]>
[2025-09-24T00:54:09.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab1.load_model_task manual__2025-09-24T00:53:59.377325+00:00 [queued]>
[2025-09-24T00:54:09.692+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-24T00:54:09.696+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_model_task> on 2025-09-24 00:53:59.377325+00:00
[2025-09-24T00:54:09.706+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=392) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-24T00:54:09.707+0000] {standard_task_runner.py:63} INFO - Started process 401 to run task
[2025-09-24T00:54:09.708+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1', 'load_model_task', 'manual__2025-09-24T00:53:59.377325+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmp1my41fm8']
[2025-09-24T00:54:09.709+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask load_model_task
[2025-09-24T00:54:09.731+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab1.load_model_task manual__2025-09-24T00:53:59.377325+00:00 [running]> on host 01ca18496a79
[2025-09-24T00:54:09.776+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='Airflow_Lab1' AIRFLOW_CTX_TASK_ID='load_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-09-24T00:53:59.377325+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-24T00:53:59.377325+00:00'
[2025-09-24T00:54:09.776+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-24T00:54:09.788+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-24T00:54:09.788+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/src/lab.py", line 102, in load_hierarchical_model
    df = df[["PURCHASES_FREQUENCY", "CASH_ADVANCE_FREQUENCY", "PAYMENTS", "MINIMUM_PAYMENTS"]].dropna().head(10)
         ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['PURCHASES_FREQUENCY', 'CASH_ADVANCE_FREQUENCY', 'PAYMENTS',\n       'MINIMUM_PAYMENTS'],\n      dtype='object')] are in the [columns]"
[2025-09-24T00:54:09.797+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Lab1, task_id=load_model_task, run_id=manual__2025-09-24T00:53:59.377325+00:00, execution_date=20250924T005359, start_date=20250924T005409, end_date=20250924T005409
[2025-09-24T00:54:09.803+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 44 for task load_model_task ("None of [Index(['PURCHASES_FREQUENCY', 'CASH_ADVANCE_FREQUENCY', 'PAYMENTS',\n       'MINIMUM_PAYMENTS'],\n      dtype='object')] are in the [columns]"; 401)
[2025-09-24T00:54:09.847+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-24T00:54:09.854+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-24T00:54:09.854+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
